version: '2.2'

services:
  cube:
    build: .
    image: starghost/cubejs-doris:latest
    ports:
      - 4021:4021
      - 15441:15441
    environment:
      - CUBEJS_DEV_MODE=true
      - PORT=4021
      - DEBUG_LOG=true
      - CUBEJS_LOG_LEVEL=trace
      - CUBEJS_PG_SQL_PORT=15441
      
    volumes:
      - .cube_test:/cube/conf
